# Generated by Django 4.0 on 2021-12-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_currency_stock_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
    ]
